### ISSUE TITLE
Cannot find module yargs (Docker image)

### ISSUE THREAD

**Issue by frafra** [gbif/portal16#1390]
Using the branch from #1388...

```
# docker build --tag gbif/portal16
# hcon -Rt svirt_sandbox_file_t config/
# docker run --publish 1234:80 --volume $PWD/config:/etc/portal16 --rm --name portal16 --interactive --tty gbif/portal16 
npm info it worked if it ends with ok
npm info using npm@4.2.0
npm info using node@v7.9.0
npm info lifecycle gbif-portal16@1.0.0~prestart: gbif-portal16@1.0.0
npm info lifecycle gbif-portal16@1.0.0~start: gbif-portal16@1.0.0

> gbif-portal16@1.0.0 start /usr/src/app
> NODE_ENV=prod node app.js

module.js:472
    throw err;
    ^

Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/etc/portal16/config.js:2:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

npm info lifecycle gbif-portal16@1.0.0~start: Failed to exec start script
npm ERR! Linux 5.6.15-200.fc31.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gbif-portal16@1.0.0 start: `NODE_ENV=prod node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gbif-portal16@1.0.0 start script 'NODE_ENV=prod node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gbif-portal16 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=prod node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gbif-portal16
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gbif-portal16
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2020-07-06T15_11_37_379Z-debug.log
```

**Comment by MortenHofft** [comment]
Hi @frafra 
Thank you so much for your interest in the project. May I ask what you are trying to achieve?

**Unlikely to run locally**
I'm asking because the project depends on secret keys and firewall access.

Almost all data on the website is freely available through our APIs (see https://www.gbif.org/developer)
But there are a few exceptions (participation data, login, downloads, cms prose, literature)

Occurrence/dataset/publisher search and presentation could in theory be reused, but it would require a fair amount of rewriting.

**Alternatives**
You are likely better of building of our APIs, and we will be happy to help getting you started.

We are also in the process of building a more standalone project for reusing occurrence search, that might have interest as that matures.

Thanks

**Comment by frafra** [comment]
Hi @MortenHofft,
Sure! I was just trying to spin up a GBIF instance for testing and to evaluate if it could be further extended for the https://livingnorway.no/ initiative, instead of developing something custom, while contributing back to the original source code as much as possible. That is one of the scenario we are exploring.

**Comment by MortenHofft** [comment]
This item from the GBIF work program 2020 might have your interest
https://docs.gbif.org/2020-work-programme/en/#_activity_1c_equip_participant_nodes

> The Secretariat will design and implement user interfaces and services necessary to support simple hosted portals. The initial deployment will be of the BID programme portal followed by exploration of country portals and an exemplar virtual natural history collection. Discussions will determine whether such services should be restricted to Voting Participant countries and/or institutions that contribute a fee to create institutional portals.

**Comment by timrobertson100** [comment]
@frafra - perhaps Morten could join in the Living Norway symposium this year, relating to this?

**Comment by frafra** [comment]
@timrobertson100 Sure, it seems a great idea to me :)
https://livingnorway.no/towards-open-science-in-applied-ecology/
