### ISSUE TITLE
500 error on Directory page on demo, error msg on dev

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#154]
Directory throwing up a 500 error here:
http://demo.gbif.org/directory/contact-us

Detailed error message on gbif-dev is:

>Error: Error: null in getCommitteeContacts() while accessing http://api.gbif.org/v1/directory/committee/nodes_steering_group
Error: Error: Error: null in getCommitteeContacts() while accessing http://api.gbif.org/v1/directory/committee/nodes_steering_group
    at /var/www/portal16/app/models/gbifdata/directory/directory.js:130:26
    at _rejected (/var/www/portal16/node_modules/q/q.js:844:24)
    at /var/www/portal16/node_modules/q/q.js:870:30
    at Promise.when (/var/www/portal16/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/var/www/portal16/node_modules/q/q.js:788:41)
    at /var/www/portal16/node_modules/q/q.js:604:44
    at runSingle (/var/www/portal16/node_modules/q/q.js:137:13)
    at flush (/var/www/portal16/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by cgendreau** [comment]
This is working on the dev and uat Directory API but not on the prod one.
Latest configurations are not in yet.

**Comment by MortenHofft** [comment]
solved - I suppose by latest Directory release.
