### ISSUE TITLE
dataset detail page throws errors

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#33]
I get a lot of console errors when visiting the dataset details page. Not sure exactly when it happens, but both times I've noticed it I was near the infinite scroll.
The client also throws errors and does around 3200 calls to endpoints a la
`
http://localhost:7000/occurrence-download-dataset/81c5a091-6e94-40db-a2a4-48f4de42d410?limit=5&offset=14645
`
after 10 minuttes they still haven't resolved and a 1000 has failed.

And the client code downloadEventsTableCtrl throws errors.

server side express throws this:
`Error: Error: connect ETIMEDOUT 130.226.238.135:80
    at /Users/mortenhofft/Documents/dev/work/gbif/portal16/app/controllers/dataset/details/datasetDetails.ctrl.js:664:22
    at _rejected (/Users/mortenhofft/Documents/dev/work/gbif/portal16/node_modules/q/q.js:844:24)
    at /Users/mortenhofft/Documents/dev/work/gbif/portal16/node_modules/q/q.js:870:30
    at Promise.when (/Users/mortenhofft/Documents/dev/work/gbif/portal16/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/Users/mortenhofft/Documents/dev/work/gbif/portal16/node_modules/q/q.js:788:41)
    at /Users/mortenhofft/Documents/dev/work/gbif/portal16/node_modules/q/q.js:604:44
    at runSingle (/Users/mortenhofft/Documents/dev/work/gbif/portal16/node_modules/q/q.js:137:13)
    at flush (/Users/mortenhofft/Documents/dev/work/gbif/portal16/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Error: Error: connect ETIMEDOUT 130.226.238.135:80
    at /Users/mortenhofft/Documents/dev/work/gbif/portal16/app/controllers/dataset/details/datasetDetails.ctrl.js:664:22
    at _rejected (/Users/mortenhofft/Documents/dev/work/gbif/portal16/node_modules/q/q.js:844:24)
    at /Users/mortenhofft/Documents/dev/work/gbif/portal16/node_modules/q/q.js:870:30
    at Promise.when (/Users/mortenhofft/Documents/dev/work/gbif/portal16/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/Users/mortenhofft/Documents/dev/work/gbif/portal16/node_modules/q/q.js:788:41)
    at /Users/mortenhofft/Documents/dev/work/gbif/portal16/node_modules/q/q.js:604:44
    at runSingle (/Users/mortenhofft/Documents/dev/work/gbif/portal16/node_modules/q/q.js:137:13)
    at flush (/Users/mortenhofft/Documents/dev/work/gbif/portal16/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

**Comment by MortenHofft** [comment]
not relevant anymore. infinite scroll removed as rollups seems more useful to publishers.
