### ISSUE TITLE
Frequent error: Failing relations in participant request

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#665]
We regularly get errors in the logs related to participants. And it seems it isn't really an error, but a misunderstanding. An example is the former GBIF participant ISIS.
 failing query: https://www.gbif.org/search?q=International%20Species%20Information%20System

```
error: {
      "name": "AssertionError",
      "message": "expected { Object (id, name, ...) } to have property 'countryCode'",
      "showDiff": false,
      "actual": {
        "id": 299,
        "name": "International Species Information System",
        "abbreviatedName": "ISIS",
        "type": "OTHER",
        "participationStatus": "FORMER",
        "participantUrl": "http://www.isis.org",
        "membershipStart": "2006-05",
        "mou2001Date": "2006-05-30T22:00:00.000+0000",
        "mou2007Date": "2006-12-19T23:00:00.000+0000",
        "mou2007Signatory": "Mr. Nathan Flesness, Executive Director, ISIS",
        "createdBy": "anmnielsen",
        "modifiedBy": "anmnielsen",
        "created": "2008-06-19T01:40:19.000+0000",
        "modified": "2014-06-18T09:19:32.000+0000",
        "people": [],
        "nodes": [
          {
            "id": 94,
            "name": "International Species Information System",
            "acronym": "ISIS",
            "people": [],
            "href": "http://api.gbif.org/v1/directory/node/94"
          }
        ]
      },
      "stack": "AssertionError: expected { Object (id, name, ...) } to have property 'countryCode'\n    at expandParticipant (/Users/hoefft/dev/git/gbif/portal16/app/models/node/participant.js:113:33)\n    at /Users/hoefft/dev/git/gbif/portal16/app/models/node/participant.js:60:17\n    at process._tickCallback (internal/process/next_tick.js:109:7)"
    }
```

**Comment by MortenHofft** [comment]
This also keeps the code from logging errors when there is no node for a participant. All participants should have a node, but in reality this isn't the case.
