### ISSUE TITLE
unhandled promise rejection

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#668]
@thomasstjerne I've looked at our logs to see what errors we have. I see this among many others:

```
{"name":"portal16","hostname":"prodnode-vh.gbif.org","pid":7432,"level":50,"msg":"Unhandled Rejection at root: Promise  Rejected {\n  id: 45,\n  value: \n   TypeError: Cannot read property 'extensions' of undefined\n       at /var/www/portal16/app/controllers/api/dwcextensions/dwcExtensions.ctrl.js:29:43\n       at tryCatchReject (/var/www/portal16/node_modules/when/lib/makePromise.js:845:30)\n       at runContinuation1 (/var/www/portal16/node_modules/when/lib/makePromise.js:804:4)\n       at Fulfilled.when (/var/www/portal16/node_modules/when/lib/makePromise.js:592:4)\n       at Pending.run (/var/www/portal16/node_modules/when/lib/makePromise.js:483:13)\n       at Scheduler._drain (/var/www/portal16/node_modules/when/lib/Scheduler.js:62:19)\n       at Scheduler.drain (/var/www/portal16/node_modules/when/lib/Scheduler.js:27:9)\n       at _combinedTickCallback (internal/process/next_tick.js:73:7)\n       at process._tickCallback (internal/process/next_tick.js:104:9),\n  handled: false,\n  reported: true }  reason:  TypeError: Cannot read property 'extensions' of undefined\n    at /var/www/portal16/app/controllers/api/dwcextensions/dwcExtensions.ctrl.js:29:43\n    at tryCatchReject (/var/www/portal16/node_modules/when/lib/makePromise.js:845:30)\n    at runContinuation1 (/var/www/portal16/node_modules/when/lib/makePromise.js:804:4)\n    at Fulfilled.when (/var/www/portal16/node_modules/when/lib/makePromise.js:592:4)\n    at Pending.run (/var/www/portal16/node_modules/when/lib/makePromise.js:483:13)\n    at Scheduler._drain (/var/www/portal16/node_modules/when/lib/Scheduler.js:62:19)\n    at Scheduler.drain (/var/www/portal16/node_modules/when/lib/Scheduler.js:27:9)\n    at _combinedTickCallback (internal/process/next_tick.js:73:7)\n    at process._tickCallback (internal/process/next_tick.js:104:9)","time":"2018-02-12T02:01:02.199Z","v":0}
```

This will make the site crash and restart

https://github.com/gbif/portal16/blob/master/app/controllers/api/dwcextensions/dwcExtensions.ctrl.js#L44

I can't say why it happens, but the error handling seems wrong. It shouldn't throw it I assume. Rather just return an error to the client?

**Comment by MortenHofft** [comment]
I've changed it to return an error to the caller. But I haven't looked into why it fails in the first place.

**Comment by MortenHofft** [comment]
closed in favour of https://github.com/gbif/portal16/issues/670
