### ISSUE TITLE
Unhandled rejection in species ctrl

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#669]
Cleaning logs I looked for unhandled rejections:

https://github.com/gbif/portal16/blob/master/app/controllers/api/species/key/speciesKey.ctrl.js#L169

This will make the site crash and restart

```
{"name":"portal16","hostname":"prodnode-vh.gbif.org","pid":13459,"level":50,"msg":"Unhandled Rejection at root: Promise  Rejected {\n  id: 106,\n  value: \n   TypeError: Cannot read property 'forEach' of undefined\n       at /var/www/portal16/app/controllers/api/species/key/speciesKey.ctrl.js:169:34\n       at tryCatchReject (/var/www/portal16/node_modules/when/lib/makePromise.js:845:30)\n       at runContinuation1 (/var/www/portal16/node_modules/when/lib/makePromise.js:804:4)\n       at Fulfilled.when (/var/www/portal16/node_modules/when/lib/makePromise.js:592:4)\n       at Pending.run (/var/www/portal16/node_modules/when/lib/makePromise.js:483:13)\n       at Scheduler._drain (/var/www/portal16/node_modules/when/lib/Scheduler.js:62:19)\n       at Scheduler.drain (/var/www/portal16/node_modules/when/lib/Scheduler.js:27:9)\n       at _combinedTickCallback (internal/process/next_tick.js:73:7)\n       at process._tickCallback (internal/process/next_tick.js:104:9),\n  handled: false,\n  reported: true }  reason:  TypeError: Cannot read property 'forEach' of undefined\n    at /var/www/portal16/app/controllers/api/species/key/speciesKey.ctrl.js:169:34\n    at tryCatchReject (/var/www/portal16/node_modules/when/lib/makePromise.js:845:30)\n    at runContinuation1 (/var/www/portal16/node_modules/when/lib/makePromise.js:804:4)\n    at Fulfilled.when (/var/www/portal16/node_modules/when/lib/makePromise.js:592:4)\n    at Pending.run (/var/www/portal16/node_modules/when/lib/makePromise.js:483:13)\n    at Scheduler._drain (/var/www/portal16/node_modules/when/lib/Scheduler.js:62:19)\n    at Scheduler.drain (/var/www/portal16/node_modules/when/lib/Scheduler.js:27:9)\n    at _combinedTickCallback (internal/process/next_tick.js:73:7)\n    at process._tickCallback (internal/process/next_tick.js:104:9)","time":"2018-02-12T13:01:11.508Z","v":0}
```

This is similar to https://github.com/gbif/portal16/issues/668

**Comment by MortenHofft** [comment]
closed in favour of https://github.com/gbif/portal16/issues/670
